### ISSUE TITLE
Declare a sprite image in a gss file

### ISSUE THREAD

**Issue by freddyboucher** [gwtproject/gwt#9322]
Hi,
I'm using GWT 2.7.0 and I'd like to declare a **sprite** image in my **gss** file without using **ImageResource** neither **ClientBundle**. 
Something like:

```css
.logout {
    gwt-sprite: "../images/my-image.png";
    display: block;
    cursor: pointer;
}
```
Is it possible? 
Probably a question for @jDramaix 
Thanks

Originally posted in [Stackoverflow](http://stackoverflow.com/questions/36634457/gwt-how-to-declare-a-sprite-image-in-a-gss-file)

**Comment by jnehlmeier** [comment]
Its a ClientBundle feature to combine all ImagesResources found in a specific ClientBundle into a single large image sprite. The old `@sprite` and the new `gwt-sprite` rules are used to target a specific image inside that sprite. As the ClientBundle generator has generated the large image sprite it does know where to find all the smaller, combined images. So all the `@sprite` /  `gwt-sprite` rules in your CSS can automatically be replaced with the actual CSS code to show the desired image within the image sprite.

You can not use `@sprite` and `gwt-sprite` on its own without ClientBundle.

But of course you can use your own sprite images by manually defining the correct CSS code, e.g.

```css
.logout {
    /* position the desired smaller image within my-image to the top-left corner of .logout element by repositioning the large sprite image */
    background: url("../images/my-image.png") 25px 20px;
    /* define the width/height of the .logout element to match the size of the smaller image within the image sprite */
    width: 100px;
    height: 50px;
    display: block;
    cursor: pointer;
}
```
